syntax = "proto3";
package benchmark;

service ProcessadorService{
    //1. Unary
    //Envia uma única requisição e recebe uma única resposta.
    rpc ProcessarDados (DadosRequest) returns (DadosResponse);
  
    //2. Server Streaming
    //Envia uma única requisição e recebe um fluxo (stream) de respostas.
    rpc ProcessarStreamServidor (DadosRequest) returns (stream DadosResponse);
  
    //3. Client Streaming
    //Envia um fluxo (stream) de requisições e recebe uma única resposta no final.
    rpc ProcessarStreamCliente (stream DadosRequest) returns (DadosResponse);

    //4. Bidirectional Streaming
    //Envia um fluxo de requisições e recebe um fluxo de respostas simultaneamente.
    rpc ProcessarStreamBidirecional (stream DadosRequest) returns (stream DadosResponse);
}

message DadosRequest{
    string payload = 1;
    int32 nivel_complexidade = 2; 
}

message DadosResponse{
    string resultado = 1;
    double tempo_processamento_ms = 2;
}